// Decompiled with JetBrains decompiler
// Type: Mafi.Base.Prototypes.Research.FarmingResearchData
// Assembly: Mafi.Base, Version=0.6.3.0, Culture=neutral, PublicKeyToken=null
// MVID: 189C759C-DBD6-48EA-AEF6-5D1D80F045F4
// Assembly location: D:\GameLibrary\SteamLibrary\steamapps\common\Captain of Industry\Captain of Industry_Data\Managed\Mafi.Base.dll
// XML documentation location: D:\GameLibrary\SteamLibrary\steamapps\common\Captain of Industry\Captain of Industry_Data\Managed\Mafi.Base.xml

using eLxG93FZl5M3yHxFGb;
using Mafi.Core;
using Mafi.Core.Mods;
using Mafi.Core.Prototypes;
using Mafi.Core.Research;

#nullable disable
namespace Mafi.Base.Prototypes.Research
{
  internal class FarmingResearchData : IResearchNodesData, IModData
  {
    public void RegisterData(ProtoRegistrator registrator)
    {
      registrator.ResearchNodeProtoBuilder.Start("Basic farming", Ids.Research.BasicFarming).Description("Basic farming of potatoes. We just need to hope it will rain.", "description of a research node in the research tree").AddLayoutEntityToUnlock(Ids.Buildings.FarmT1).AddCropToUnlock(Ids.Crops.Potato).AddProductToUnlock(Ids.Products.Potato, hideInUi: true).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Irrigated farms", Ids.Research.FarmingT2).AddLayoutEntityToUnlock(Ids.Buildings.FarmT2).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Tree planting", Ids.Research.TreePlanting).AddLayoutEntityToUnlock(Ids.Buildings.ForestryTower).AddVehicleToUnlock(Ids.Vehicles.TreePlanterT1).AddCropToUnlock(Ids.Crops.TreeSapling).AddProductToUnlock(Ids.Products.TreeSapling, hideInUi: true).AddTreeToUnlock(Ids.Trees.FirTree).AddTreeToUnlock(Ids.Trees.SpruceTree).AddTreeToUnlock(Ids.Trees.BirchTree).AddTreeToUnlock(Ids.Trees.MapleTree).AddTreeToUnlock(Ids.Trees.OakTree).AddTreeToUnlock(Ids.Trees.PalmTree).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Crop rotation", Ids.Research.CropRotation).UseDescriptionFrom(IdsCore.Technology.CropRotation).AddTechnologyToUnlock(IdsCore.Technology.CropRotation).AddCropToUnlock(Ids.Crops.GreenManure).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Greenhouse", Ids.Research.FarmingT3).AddLayoutEntityToUnlock(Ids.Buildings.FarmT3).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Greenhouse II", Ids.Research.FarmingT4).AddLayoutEntityToUnlock(Ids.Buildings.FarmT4).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Burner", Ids.Research.Burner).AddMachineToUnlock(Ids.Machines.SolidBurner).AddRecipeToUnlock(Ids.Recipes.LandfillBurning).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Vegetables farming", Ids.Research.Vegetables).Description("Enables to grow & harvest vegetables in farms.", "description of a research node in the research tree").AddCropToUnlock(Ids.Crops.Vegetables).AddProductToUnlock(Ids.Products.Vegetables, hideInUi: true).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Corn farming", Ids.Research.CornCrop).Description("Enables to grow & harvest corn in farms.", "description of a research node in the research tree").AddRequiredProto(Ids.Technology.CornSeeds).AddCropToUnlock(Ids.Crops.Corn).AddProductToUnlock(Ids.Products.Corn, hideInUi: true).AddRecipeToUnlock(Ids.Recipes.CornMilling).AddRecipeToUnlock(Ids.Recipes.AnimalFeedFromCorn).AddRecipeToUnlock(Ids.Recipes.AnimalFeedFromCornT2, true).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Wheat farming & processing", Ids.Research.WheatCrop).AddCropToUnlock(Ids.Crops.Wheat).AddProductToUnlock(Ids.Products.Bread, hideInUi: true).AddMachineToUnlock(Ids.Machines.FoodMill).AddMachineToUnlock(Ids.Machines.BakingUnit).AddRecipeToUnlock(Ids.Recipes.WheatMilling).AddRecipeToUnlock(Ids.Recipes.BreadProduction).AddRecipeToUnlock(Ids.Recipes.WheatDigestion).AddRecipeToUnlock(Ids.Recipes.AnimalFeedFromWheat).AddRecipeToUnlock(Ids.Recipes.AnimalFeedFromWheatT2, true).AddRecipeToUnlock(Ids.Recipes.AnimalFeedBurning).AddRecipeToUnlock(Ids.Recipes.SteamGenerationAnimalFeed).AddRequiredProto(Ids.Technology.WheatSeeds).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Soybean farming", Ids.Research.SoybeanCrop).AddMachineToUnlock(Ids.Machines.FoodProcessor).AddCropToUnlock(Ids.Crops.Soybeans).AddProductToUnlock(Ids.Products.Tofu, hideInUi: true).AddRecipeToUnlock(Ids.Recipes.TofuProduction).AddRecipeToUnlock(Ids.Recipes.AnimalFeedFromSoybean).AddRecipeToUnlock(Ids.Recipes.AnimalFeedFromSoybeanT2, true).AddRequiredProto(Ids.Technology.SoybeansSeeds).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Canola", Ids.Research.Canola).AddCropToUnlock(Ids.Crops.Canola).AddRecipeToUnlock(Ids.Recipes.CanolaMilling).AddRequiredProto(Ids.Technology.CanolaSeeds).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Sugar cane", Ids.Research.SugarCane).AddCropToUnlock(Ids.Crops.SugarCane).AddProductToUnlock(Ids.Products.Sugar, true).AddRecipeToUnlock(Ids.Recipes.SugarRefiningCane).AddRecipeToUnlock(Ids.Recipes.SugarToEthanolFermentation).AddRequiredProto(Ids.Technology.SugarCaneSeeds).AddRecipeToUnlock(Ids.Recipes.BiomassBurning).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Chicken farm", Ids.Research.ChickenFarm).AddProductToUnlock(Ids.Products.Chicken).AddProductToUnlock(Ids.Products.Eggs).AddMachineToUnlock(Ids.Machines.FoodProcessor).AddLayoutEntityToUnlock(Ids.Buildings.ChickenFarm).AddRecipeToUnlock(Ids.Recipes.MeatProcessing).AddRecipeToUnlock(Ids.Recipes.MeatTrimmingsCompost).AddRecipeToUnlock(Ids.Recipes.MeatTrimmingsCompostT2, true).AddRecipeToUnlock(Ids.Recipes.MeatTrimmingsDigestion).AddRecipeToUnlock(Ids.Recipes.AnimalFeedFromPotato).AddRecipeToUnlock(Ids.Recipes.AnimalFeedFromPotatoT2, true).AddRecipeToUnlock(Ids.Recipes.MeatTrimmingsBurning).AddRecipeToUnlock(Ids.Recipes.ChickenCarcassBurning).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Snacks production", Ids.Research.SnacksProduction).AddProductToUnlock(Ids.Products.Snack, true).AddRecipeToUnlock(Ids.Recipes.SnackProductionCorn).AddRecipeToUnlock(Ids.Recipes.SnackProductionPotato).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Fruit", Ids.Research.Fruit).Description("Enables to grow & harvest fruit in greenhouses.", "description of a research node in the research tree").AddRequiredProto(Ids.Technology.FruitSeeds).AddCropToUnlock(Ids.Crops.Fruits).AddProductToUnlock(Ids.Products.Fruit, hideInUi: true).AddProductToUnlock(Ids.Products.Cake, hideInUi: true).AddRecipeToUnlock(Ids.Recipes.CakeProduction).AddRecipeToUnlock(Ids.Recipes.FruitDigestion).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Sausage production", Ids.Research.SausageProduction).AddProductToUnlock(Ids.Products.Sausage, true).AddRecipeToUnlock(Ids.Recipes.SausageProduction).AddRecipeToUnlock(Ids.Recipes.MeatProcessingTrimmings).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Food packing", Ids.Research.FoodPacking).Description("Enables to pack food in order to sell it via contracts.", "description of a research node in the research tree").AddProductToUnlock(Ids.Products.FoodPack, true).AddRecipeToUnlock(Ids.Recipes.FoodPackAssemblyEggs).AddRecipeToUnlock(Ids.Recipes.FoodPackAssemblyMeat).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Groundwater pump", Ids.Research.UndergroundWater).AddMachineToUnlock(Ids.Machines.LandWaterPump, true).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Wastewater treatment", Ids.Research.WaterTreatment).AddMachineToUnlock(Ids.Machines.WaterTreatmentPlant).AddRecipeToUnlock(Ids.Recipes.WaterTreatment).AddRecipeToUnlock(Ids.Recipes.SludgeDigestion).AddRecipeToUnlock(Ids.Recipes.SludgeBurning).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Wastewater treatment II", Ids.Research.WaterTreatment2).Description("A more efficient wastewater treatment process.", "description of a research node in the research tree").AddRecipeToUnlock(Ids.Recipes.WaterTreatmentT2).AddRecipeToUnlock(Ids.Recipes.FilterMediaMixing).AddRecipeToUnlock(Ids.Recipes.FilterMediaMixingM).AddRecipeToUnlock(Ids.Recipes.FilterMediaMixingT2, true).AddRecipeToUnlock(Ids.Recipes.FilterMediaMixingMT2, true).AddProductIcon(Ids.Products.FilterMedia).AddProductIcon(Ids.Products.Sludge).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Salt production", Ids.Research.SaltProduction).UseDescriptionFrom((Proto.ID) Ids.Machines.EvaporationPond).AddMachineToUnlock(Ids.Machines.OceanWaterPumpT1, true).AddMachineToUnlock(Ids.Machines.EvaporationPond).AddMachineToUnlock(Ids.Machines.EvaporationPondHeated).AddRecipeToUnlock(Ids.Recipes.SaltMaking).AddRecipeToUnlock(Ids.Recipes.SaltMakingHeated).AddRecipeToUnlock(Ids.Recipes.SaltMakingFromBrine).AddRecipeToUnlock(Ids.Recipes.SaltMakingFromBrineHeated).AddRecipeToUnlock(Ids.Recipes.BrineMaking).AddRecipeToUnlock(Ids.Recipes.BrineMakingHeated).AddRecipeToUnlock(Ids.Recipes.BrineProduction).AddProductIcon(Ids.Products.Salt).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Basic desalination", Ids.Research.ThermalDesalinationBasic).Description("Enables to repurpose basic distiller for water desalination. It is not very efficient.", "description of a research node in the research tree").AddMachineToUnlock(Ids.Machines.OceanWaterPumpT1, true).AddRecipeToUnlock(Ids.Recipes.WaterDesalinationBasic).AddProductIcon(Ids.Products.Water).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Thermal desalination", Ids.Research.ThermalDesalination).UseDescriptionFrom((Proto.ID) Ids.Machines.ThermalDesalinator).AddMachineToUnlock(Ids.Machines.ThermalDesalinator).AddMachineToUnlock(Ids.Machines.OceanWaterPumpT1, true).AddMachineToUnlock(Ids.Machines.OceanWaterPumpLarge, true).AddRecipeToUnlock(Ids.Recipes.DesalinationFromHP).AddRecipeToUnlock(Ids.Recipes.DesalinationFromLP).AddProductIcon(Ids.Products.Water).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Vacuum desalination", Ids.Research.VacuumDesalination).Description("Enables to utilize depleted steam for desalination.", "description of a research node in the research tree").AddRecipeToUnlock(Ids.Recipes.DesalinationFromDepleted).AddProductIcon(Ids.Products.Water).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Chemical plant & paper", Ids.Research.ChemicalPlant).AddMachineToUnlock(Ids.Machines.ChemicalPlant).AddMachineToUnlock(Ids.Machines.Shredder).AddProductIcon(Ids.Products.Paper).AddRecipeToUnlock(Ids.Recipes.PaperProduction).AddRecipeToUnlock(Ids.Recipes.ShreddingWood).AddRecipeToUnlock(Ids.Recipes.SteamGenerationWood).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Fertilizers", Ids.Research.Fertilizers).Description("Provides industrial production of chemical fertilizer.", "description of a research node in the research tree").AddProductIcon(Ids.Products.FertilizerChemical).AddProductIcon(Ids.Products.FertilizerChemical2).AddRecipeToUnlock(Ids.Recipes.FertilizerProduction).AddRecipeToUnlock(Ids.Recipes.AmmoniaSynthesis).AddRecipeToUnlock(Ids.Recipes.Fertilizer2Production).AddRecipeToUnlock(Ids.Recipes.Fertilizer2ProductionT2, true).AddRecipeToUnlock(Ids.Recipes.FertilizerChem1Dumping).AddRecipeToUnlock(Ids.Recipes.FertilizerChem2Dumping).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Chemical plant II", Ids.Research.ChemicalPlant2).UseDescriptionFrom((Proto.ID) Ids.Machines.ChemicalPlant2).AddMachineToUnlock(Ids.Machines.ChemicalPlant2).AddRecipeToUnlock(Ids.Recipes.FertilizerProductionT2).AddRecipeToUnlock(Ids.Recipes.AmmoniaSynthesisT2).AddRecipeToUnlock(Ids.Recipes.FuelGasSynthesis).AddRecipeToUnlock(Ids.Recipes.GraphiteProductionT2).AddRecipeToUnlock(Ids.Recipes.PaperProductionT2).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Electrolysis", Ids.Research.Electrolysis).UseDescriptionFrom((Proto.ID) Ids.Machines.Electrolyzer).AddMachineToUnlock(Ids.Machines.Electrolyzer).AddRecipeToUnlock(Ids.Recipes.WaterElectrolysis).AddRecipeToUnlock(Ids.Recipes.AmmoniaElectrolysis).AddRecipeToUnlock(Ids.Recipes.BrineElectrolysis).AddRecipeToUnlock(Ids.Recipes.FlareHydrogen, true).AddRecipeToUnlock(Ids.Recipes.SmokeStackOxygen, true).AddRecipeToUnlock(Ids.Recipes.SmokeStackLargeOxygen, true).AddProductIcon(Ids.Products.Hydrogen).AddProductIcon(Ids.Products.Chlorine).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Electrolyzer II", Ids.Research.Electrolysis2).UseDescriptionFrom((Proto.ID) Ids.Machines.ElectrolyzerT2).AddMachineToUnlock(Ids.Machines.ElectrolyzerT2).AddRecipeToUnlock(Ids.Recipes.WaterElectrolysisT2).AddRecipeToUnlock(Ids.Recipes.AmmoniaElectrolysisT2).AddRecipeToUnlock(Ids.Recipes.BrineElectrolysisT2).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("CO2 recycling", Ids.Research.CarbonDioxideRecycling).AddProductIcon(Ids.Products.CarbonDioxide).AddRecipeToUnlock(Ids.Recipes.GraphiteProductionCo2).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Organic fertilizer", Ids.Research.OrganicFertilizer).AddMachineToUnlock(Ids.Machines.IndustrialMixer).AddRecipeToUnlock(Ids.Recipes.OrganicFertilizerProduction).AddRecipeToUnlock(Ids.Recipes.OrganicFertilizerProductionT2, true).AddRecipeToUnlock(Ids.Recipes.AnimalFeedCompost).AddRecipeToUnlock(Ids.Recipes.AnimalFeedCompostT2, true).AddRecipeToUnlock(Ids.Recipes.BiomassCompost).AddRecipeToUnlock(Ids.Recipes.BiomassCompostT2, true).AddRecipeToUnlock(Ids.Recipes.DirtMixing).AddRecipeToUnlock(Ids.Recipes.DirtMixingT2, true).AddRecipeToUnlock(Ids.Recipes.FertilizerOrganicDumping).AddProductIcon(Ids.Products.Compost).AddProductIcon(Ids.Products.FertilizerOrganic).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Fermentation", Ids.Research.Fermentation).AddMachineToUnlock(Ids.Machines.FermentationTank).AddProductIcon(Ids.Products.Ethanol).AddRecipeToUnlock(Ids.Recipes.CornToEthanolFermentation).AddRecipeToUnlock(Ids.Recipes.RubberProductionEthanol).AddRecipeToUnlock(Ids.Recipes.SteamGenerationEthanol).AddRecipeToUnlock(Ids.Recipes.FlareEthanol).SetAnyParentCanUnlock().BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Hospital", Ids.Research.Hospital).UseDescriptionFrom((Proto.ID) Ids.Buildings.Clinic).AddLayoutEntityToUnlock(Ids.Buildings.Clinic).AddProductIcon(Ids.Products.MedicalSupplies).AddRecipeToUnlock(Ids.Recipes.MedicalEquipmentAssemblyT1).AddRecipeToUnlock(Ids.Recipes.MedicalEquipmentAssemblyT2, true).AddRecipeToUnlock(Ids.Recipes.DisinfectantProduction).AddRecipeToUnlock(Ids.Recipes.DisinfectantProductionT2, true).AddRecipeToUnlock(Ids.Recipes.MedicalSuppliesAssemblyT1).AddRecipeToUnlock(Ids.Recipes.MedicalSuppliesAssemblyT2, true).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Medical supplies II", Ids.Research.MedicalSupplies2).AddProductIcon(Ids.Products.MedicalSupplies2).AddRecipeToUnlock(Ids.Recipes.AntibioticsFermentation).AddRecipeToUnlock(Ids.Recipes.MedicalSupplies2AssemblyT1).AddRecipeToUnlock(Ids.Recipes.MedicalSupplies2AssemblyT2, true).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Medical supplies III", Ids.Research.MedicalSupplies3).AddCropToUnlock(Ids.Crops.Poppy).AddProductIcon(Ids.Products.Poppy).AddProductIcon(Ids.Products.MedicalSupplies3).AddRecipeToUnlock(Ids.Recipes.AnestheticsProduction).AddRecipeToUnlock(Ids.Recipes.MorphineProduction).AddRecipeToUnlock(Ids.Recipes.MedicalSupplies3AssemblyT1).AddRecipeToUnlock(Ids.Recipes.MedicalSupplies3AssemblyT2).AddRecipeToUnlock(Ids.Recipes.PoppyDigestion).AddRequiredProto(Ids.Technology.PoppySeeds).BuildAndAdd();
    }

    public FarmingResearchData()
    {
      MBiHIp97M4MqqbtZOh.chMFXj727();
      // ISSUE: explicit constructor call
      base.\u002Ector();
    }
  }
}
