// Decompiled with JetBrains decompiler
// Type: Mafi.Base.Prototypes.Research.MiningAndSmeltingResearchData
// Assembly: Mafi.Base, Version=0.6.3.0, Culture=neutral, PublicKeyToken=null
// MVID: 189C759C-DBD6-48EA-AEF6-5D1D80F045F4
// Assembly location: D:\GameLibrary\SteamLibrary\steamapps\common\Captain of Industry\Captain of Industry_Data\Managed\Mafi.Base.dll
// XML documentation location: D:\GameLibrary\SteamLibrary\steamapps\common\Captain of Industry\Captain of Industry_Data\Managed\Mafi.Base.xml

using eLxG93FZl5M3yHxFGb;
using Mafi.Core.Entities.Static;
using Mafi.Core.Mods;
using Mafi.Core.Prototypes;
using Mafi.Core.Research;
using Mafi.Localization;

#nullable disable
namespace Mafi.Base.Prototypes.Research
{
  internal class MiningAndSmeltingResearchData : IResearchNodesData, IModData
  {
    public void RegisterData(ProtoRegistrator registrator)
    {
      registrator.ResearchNodeProtoBuilder.Start("Iron smelting (from scrap)", Ids.Research.IronSmeltingScrap).Description("Production of iron from metal scraps.", "description of a research node in the research tree").AddMachineToUnlock(Ids.Machines.SmeltingFurnaceT1).AddRecipeToUnlock(Ids.Recipes.IronSmeltingT1Scrap).AddMachineToUnlock(Ids.Machines.Caster).AddMachineToUnlock(Ids.Machines.CharcoalMaker, true).AddRecipeToUnlock(Ids.Recipes.IronCasting).AddTransportToUnlock(Ids.Transports.MoltenMetalChannel).AddMachineToUnlock(Ids.Machines.SmokeStack).AddRecipeToUnlock(Ids.Recipes.SmokeStackExhaust, true).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Settlement waste", Ids.Research.SettlementWaste).Description("Basic collection and disposal of waste from settlements.", "description of a research node in the research tree").AddLayoutEntityToUnlock(Ids.Buildings.SettlementLandfillModule).AddProductToUnlock(Ids.Products.Waste, true).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Vehicles & mining", Ids.Research.VehicleAndMining).Description("Excavator & mining tower to enable mining raw materials. And more trucks to reinforce our logistics.", "description of a research node in the research tree").AddLayoutEntityToUnlock(Ids.Buildings.VehiclesDepot).AddVehicleToUnlock(Ids.Vehicles.ExcavatorT1).AddVehicleToUnlock(Ids.Vehicles.TruckT1.Id).AddVehicleToUnlock(Ids.Vehicles.TreeHarvesterT1).AddLayoutEntityToUnlock(Ids.Buildings.MineTower).AddLayoutEntityToUnlock(Ids.Buildings.StorageLoose).AddLayoutEntityToUnlock(Ids.Buildings.OreSortingPlantT1).AddRecipeToUnlock(Ids.Recipes.IronSmeltingT1Coal).AddRecipeToUnlock(Ids.Recipes.VehicleParts1AssemblyT1).AddProductToUnlock(Ids.Products.Rock, hideInUi: true).AddProductToUnlock(Ids.Products.Dirt, hideInUi: true).AddProductToUnlock(Ids.Products.Sand, hideInUi: true).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Copper refinement", Ids.Research.CopperRefinement).Description("Copper electrolysis enables us to reach 99% pure copper. This way we can leverage its properties to the maximum.", "description of a research node in the research tree").AddMachineToUnlock(Ids.Machines.CopperElectrolysis).AddRecipeToUnlock(Ids.Recipes.CopperSmeltingT1).AddRecipeToUnlock(Ids.Recipes.CopperSmeltingT1Scrap).AddRecipeToUnlock(Ids.Recipes.CopperCasting).AddRecipeToUnlock(Ids.Recipes.CopperElectrolysisWithWater).AddProductIcon(Ids.Products.Copper).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Concrete production", Ids.Research.ConcreteAdvanced).AddProductIcon(Ids.Products.ConcreteSlab).AddMachineToUnlock(Ids.Machines.RotaryKiln, true).AddMachineToUnlock(Ids.Machines.ConcreteMixer, true).AddMachineToUnlock(Ids.Machines.Crusher).AddRecipeToUnlock(Ids.Recipes.CpAssemblyT1).AddRecipeToUnlock(Ids.Recipes.CpAssemblyT2).AddRecipeToUnlock(Ids.Recipes.SlagCrushing).AddRecipeToUnlock(Ids.Recipes.RockCrushing).AddRecipeToUnlock(Ids.Recipes.GravelCrushing).AddRecipeToUnlock(Ids.Recipes.QuartzCrushing).AddRecipeToUnlock(Ids.Recipes.QuartzMilling).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Steel smelting", Ids.Research.SteelSmelting).Description("Process to convert iron into more durable steel.", "description of a research node in the research tree").AddMachineToUnlock(Ids.Machines.OxygenFurnace, true).AddMachineToUnlock(Ids.Machines.AirSeparator, true).AddMachineToUnlock(Ids.Machines.CasterCooled).AddRecipeToUnlock(Ids.Recipes.SteelCastingCooled).AddSurfaceToUnlock(Ids.TerrainTileSurfaces.Metal1).AddSurfaceToUnlock(Ids.TerrainTileSurfaces.Metal3).AddSurfaceToUnlock(Ids.TerrainTileSurfaces.Metal4).AddProductIcon(Ids.Products.Steel).AddRecipeToUnlock(Ids.Recipes.SmokeStackNitrogen, true).AddRecipeToUnlock(Ids.Recipes.SmokeStackLargeNitrogen, true).AddRecipeToUnlock(Ids.Recipes.SmokeStackOxygen, true).AddRecipeToUnlock(Ids.Recipes.SmokeStackLargeOxygen, true).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Exhaust filtration", Ids.Research.ExhaustFiltration).AddMachineToUnlock(Ids.Machines.ExhaustScrubber, true).AddMachineToUnlock(Ids.Machines.GasInjectionPump, true).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Copper refinement II", Ids.Research.CopperRefinement2).Description("More efficient process of copper refinement using acid.", "description of a research node in the research tree").AddRecipeToUnlock(Ids.Recipes.CopperElectrolysis).AddProductIcon(Ids.Products.Copper).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Glass making", Ids.Research.GlassSmelting).Description("Provides glass production.", "description of a research node in the research tree").AddMachineToUnlock(Ids.Machines.IndustrialMixer).AddMachineToUnlock(Ids.Machines.GlassMakerT1, true).AddRecipeToUnlock(Ids.Recipes.GlassSmelting).AddRecipeToUnlock(Ids.Recipes.GlassMixMixing).AddRecipeToUnlock(Ids.Recipes.GlassMixMixingWithAcid).AddRecipeToUnlock(Ids.Recipes.GlassSmeltingWithBroken).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Household goods", Ids.Research.HouseholdGoods).Description("Household goods for a settlement, generates extra Unity when provided.", "description of a research node in the research tree").AddLayoutEntityToUnlock(Ids.Buildings.SettlementHouseholdGoodsModule).AddProductIcon(Ids.Products.HouseholdGoods).AddRecipeToUnlock(Ids.Recipes.HouseholdGoodsAssemblyT1).AddRecipeToUnlock(Ids.Recipes.HouseholdGoodsAssemblyT2).AddEdictToUnlock(Ids.Edicts.HouseholdGoodsConsumptionIncrease).AddEdictToUnlock(Ids.Edicts.HouseholdGoodsConsumptionIncreaseT2).AddEdictToUnlock(Ids.Edicts.HouseholdGoodsConsumptionIncreaseT3).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Advanced smelting", Ids.Research.AdvancedSmelting).Description("Provides smelting with higher throughput and increased efficiency for crushed ores.", "description of a research node in the research tree").AddMachineToUnlock(Ids.Machines.SmeltingFurnaceT2, true).AddMachineToUnlock(Ids.Machines.OxygenFurnaceT2, true).AddMachineToUnlock(Ids.Machines.CasterT2).AddMachineToUnlock(Ids.Machines.CasterCooledT2).AddRecipeToUnlock(Ids.Recipes.IronCastingT2).AddRecipeToUnlock(Ids.Recipes.CopperCastingT2).AddRecipeToUnlock(Ids.Recipes.SteelCastingCooledT2).AddRecipeToUnlock(Ids.Recipes.IronOreCrushing).AddRecipeToUnlock(Ids.Recipes.CopperOreCrushing).AddProductIcon(Ids.Products.IronOreCrushed).AddProductIcon(Ids.Products.CopperOreCrushed).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Crusher (large)", Ids.Research.CrusherLarge).UseDescriptionFrom((Proto.ID) Ids.Machines.CrusherLarge).AddLayoutEntityToUnlock((StaticEntityProto.ID) Ids.Machines.CrusherLarge).AddRecipeToUnlock(Ids.Recipes.RockCrushingT2).AddRecipeToUnlock(Ids.Recipes.GravelCrushingT2).AddRecipeToUnlock(Ids.Recipes.SlagCrushingT2).AddRecipeToUnlock(Ids.Recipes.QuartzCrushingT2).AddRecipeToUnlock(Ids.Recipes.QuartzMillingT2).AddRecipeToUnlock(Ids.Recipes.IronOreCrushingT2).AddRecipeToUnlock(Ids.Recipes.CopperOreCrushingT2).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Mixer II", Ids.Research.IndustrialMixerT2).UseDescriptionFrom((Proto.ID) Ids.Machines.IndustrialMixerT2).AddLayoutEntityToUnlock((StaticEntityProto.ID) Ids.Machines.IndustrialMixerT2).AddRecipeToUnlock(Ids.Recipes.GlassMixMixingT2).AddRecipeToUnlock(Ids.Recipes.GlassMixMixingWithAcidT2).AddRecipeToUnlock(Ids.Recipes.AcidMixMixingT2).AddRecipeToUnlock(Ids.Recipes.SulfurNeutralizationT2).AddRecipeToUnlock(Ids.Recipes.BrineProductionT2).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Glass making II", Ids.Research.GlassSmeltingT2).AddMachineToUnlock(Ids.Machines.GlassMakerT2, true).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Silicon & electronics II", Ids.Research.PolySiliconProduction).AddMachineToUnlock(Ids.Machines.ArcFurnace).AddRecipeToUnlock(Ids.Recipes.SiliconSmeltingArc).AddMachineToUnlock(Ids.Machines.SiliconReactor, true).AddRecipeToUnlock(Ids.Recipes.GraphiteProductionT1).AddRecipeToUnlock(Ids.Recipes.PCBAssemblyT1).AddRecipeToUnlock(Ids.Recipes.Electronics2AssemblyT1).AddProductIcon(Ids.Products.Electronics2).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Arc furnace II", Ids.Research.ArcFurnace2).AddMachineToUnlock(Ids.Machines.ArcFurnace2, true).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Gold smelting", Ids.Research.GoldSmelting).AddMachineToUnlock(Ids.Machines.SettlingTank).AddMachineToUnlock(Ids.Machines.GoldFurnace, true).AddRecipeToUnlock(Ids.Recipes.GoldOreCrushing).AddRecipeToUnlock(Ids.Recipes.GoldOreCrushingT2).AddRecipeToUnlock(Ids.Recipes.GoldOreMilling).AddRecipeToUnlock(Ids.Recipes.GoldOreMillingT2).AddRecipeToUnlock(Ids.Recipes.GoldSettling).AddRecipeToUnlock(Ids.Recipes.ToxicSlurryDumping).AddRecipeToUnlock(Ids.Recipes.PressingOfGoldScrap).AddRecipeToUnlock(Ids.Recipes.ShreddingGoldScrap).AddProductIcon(Ids.Products.Gold).AddSurfaceToUnlock(Ids.TerrainTileSurfaces.Gold).BuildAndAdd();
      LocStr1 locStr1 = Loc.Str1(Ids.Research.RecyclingIncrease.ToString() + "__desc", "Increases overall recycling efficiency by extra {0}%.", "{0}=10");
      LocStr alreadyLocalizedStr = LocalizationManager.CreateAlreadyLocalizedStr(Ids.Research.RecyclingIncrease.ToString() + "_formatted10", locStr1.Format("10").Value);
      string iconPath = "Assets/Base/Icons/Edicts/RecyclingIncrease2.svg";
      registrator.ResearchNodeProtoBuilder.Start("Recycling increase", Ids.Research.RecyclingIncrease).Description(alreadyLocalizedStr).AddRecyclingRatioIncrease(10.Percent(), iconPath).BuildAndAdd();
      LocStr desc = Loc.Str(Ids.Research.RecyclingEdict.ToString() + "__desc", "Edicts that can be enabled to increase island's overall recycling efficiency.", "research node description");
      registrator.ResearchNodeProtoBuilder.Start("Recycling edicts", Ids.Research.RecyclingEdict).Description(desc).AddEdictToUnlock(Ids.Edicts.RecyclingIncrease).AddEdictToUnlock(Ids.Edicts.RecyclingIncreaseT2).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Recycling edicts II", Ids.Research.RecyclingEdict2).Description(desc).AddEdictToUnlock(Ids.Edicts.RecyclingIncreaseT3).AddEdictToUnlock(Ids.Edicts.RecyclingIncreaseT4).BuildAndAdd();
      registrator.ResearchNodeProtoBuilder.Start("Deconstruction efficiency", Ids.Research.DeconstructionRatioIncrease).BuildAndAdd().SetAvailability(false);
      registrator.ResearchNodeProtoBuilder.Start("Deconstruction efficiency II", Ids.Research.DeconstructionRatioIncrease2).BuildAndAdd().SetAvailability(false);
    }

    public MiningAndSmeltingResearchData()
    {
      MBiHIp97M4MqqbtZOh.chMFXj727();
      // ISSUE: explicit constructor call
      base.\u002Ector();
    }
  }
}
