// Decompiled with JetBrains decompiler
// Type: Mafi.Base.Prototypes.Research.ResearchNodesPositionSetup
// Assembly: Mafi.Base, Version=0.6.3.0, Culture=neutral, PublicKeyToken=null
// MVID: 189C759C-DBD6-48EA-AEF6-5D1D80F045F4
// Assembly location: D:\GameLibrary\SteamLibrary\steamapps\common\Captain of Industry\Captain of Industry_Data\Managed\Mafi.Base.dll
// XML documentation location: D:\GameLibrary\SteamLibrary\steamapps\common\Captain of Industry\Captain of Industry_Data\Managed\Mafi.Base.xml

using eLxG93FZl5M3yHxFGb;
using Mafi.Core.Prototypes;
using Mafi.Core.Research;

#nullable disable
namespace Mafi.Base.Prototypes.Research
{
  internal class ResearchNodesPositionSetup
  {
    private readonly ProtosDb m_protosDb;

    public ResearchNodesPositionSetup(ProtosDb protosDb)
    {
      MBiHIp97M4MqqbtZOh.chMFXj727();
      // ISSUE: explicit constructor call
      base.\u002Ector();
      this.m_protosDb = protosDb;
    }

    public void SetupPositionsAndParents()
    {
      this.setPosition(Ids.Research.CpPacking, new Vector2i(0, 20));
      this.setPosition(Ids.Research.CustomSurfaces, new Vector2i(28, 1));
      this.setPosition(Ids.Research.RepairDock, new Vector2i(12, 21));
      this.setPosition(Ids.Research.MaintenanceDepot, new Vector2i(32, 9));
      this.setPosition(Ids.Research.Recycling, new Vector2i(48, 6));
      this.setPosition(Ids.Research.Compactor, new Vector2i(56, 8));
      this.setPosition(Ids.Research.RecyclingForSettlement, new Vector2i(80, 7));
      this.setPosition(Ids.Research.BricksProduction, new Vector2i(8, 15));
      this.setPosition(Ids.Research.RotaryKilnGas, new Vector2i(64, 16));
      this.setPosition(Ids.Research.RetainingWalls, new Vector2i(28, 5));
      this.setPosition(Ids.Research.Cp2Packing, new Vector2i(16, 15));
      this.setPosition(Ids.Research.SettlementWater, new Vector2i(24, 30));
      this.setPosition(Ids.Research.FoodMarket2, new Vector2i(40, 18));
      this.setPosition(Ids.Research.SettlementPower, new Vector2i(36, 32));
      this.setPosition(Ids.Research.Housing2, new Vector2i(28, 30));
      this.setPosition(Ids.Research.Cp3Packing, new Vector2i(44, 18));
      this.setPosition(Ids.Research.Cp4Packing, new Vector2i(84, 18));
      this.setPosition(Ids.Research.BasicComputing, new Vector2i(104, 18));
      this.setPosition(Ids.Research.StatueOfMaintenance, new Vector2i(88, 8));
      this.setPosition(Ids.Research.Housing3, new Vector2i(72, 14));
      this.setPosition(Ids.Research.SettlementDecorations, new Vector2i(76, 9));
      this.setPosition(Ids.Research.TombOfCaptains, new Vector2i(100, 8));
      this.setPosition(Ids.Research.Assembler3, new Vector2i(120, 18));
      this.setPosition(Ids.Research.MicrochipProduction, new Vector2i(108, 18));
      this.setPosition(Ids.Research.MicrochipProduction2, new Vector2i(116, 15));
      this.setPosition(Ids.Research.BasicFarming, new Vector2i(0, 26));
      this.setPosition(Ids.Research.FarmingT2, new Vector2i(20, 31));
      this.setPosition(Ids.Research.TreePlanting, new Vector2i(28, 42));
      this.setPosition(Ids.Research.CropRotation, new Vector2i(20, 42));
      this.setPosition(Ids.Research.FarmingT3, new Vector2i(76, 25));
      this.setPosition(Ids.Research.FarmingT4, new Vector2i(104, 25));
      this.setPosition(Ids.Research.Burner, new Vector2i(32, 42));
      this.setPosition(Ids.Research.Vegetables, new Vector2i(24, 46));
      this.setPosition(Ids.Research.CornCrop, new Vector2i(40, 48));
      this.setPosition(Ids.Research.WheatCrop, new Vector2i(36, 46));
      this.setPosition(Ids.Research.SoybeanCrop, new Vector2i(52, 46));
      this.setPosition(Ids.Research.Canola, new Vector2i(76, 44));
      this.setPosition(Ids.Research.SugarCane, new Vector2i(92, 44));
      this.setPosition(Ids.Research.ChickenFarm, new Vector2i(60, 42));
      this.setPosition(Ids.Research.SnacksProduction, new Vector2i(72, 38));
      this.setPosition(Ids.Research.Fruit, new Vector2i(80, 28));
      this.setPosition(Ids.Research.SausageProduction, new Vector2i(96, 42));
      this.setPosition(Ids.Research.FoodPacking, new Vector2i(76, 38));
      this.setPosition(Ids.Research.UndergroundWater, new Vector2i(20, 26));
      this.setPosition(Ids.Research.WaterTreatment, new Vector2i(68, 26));
      this.setPosition(Ids.Research.WaterTreatment2, new Vector2i(92, 38));
      this.setPosition(Ids.Research.SaltProduction, new Vector2i(60, 18));
      this.setPosition(Ids.Research.ThermalDesalinationBasic, new Vector2i(32, 30));
      this.setPosition(Ids.Research.ThermalDesalination, new Vector2i(60, 22));
      this.setPosition(Ids.Research.VacuumDesalination, new Vector2i(96, 38));
      this.setPosition(Ids.Research.ChemicalPlant, new Vector2i(52, 28));
      this.setPosition(Ids.Research.Fertilizers, new Vector2i(56, 28));
      this.setPosition(Ids.Research.ChemicalPlant2, new Vector2i(92, 15));
      this.setPosition(Ids.Research.Electrolysis, new Vector2i(64, 22));
      this.setPosition(Ids.Research.Electrolysis2, new Vector2i(84, 14));
      this.setPosition(Ids.Research.CarbonDioxideRecycling, new Vector2i(116, 26));
      this.setPosition(Ids.Research.OrganicFertilizer, new Vector2i(40, 44));
      this.setPosition(Ids.Research.Fermentation, new Vector2i(60, 48));
      this.setPosition(Ids.Research.Hospital, new Vector2i(72, 48));
      this.setPosition(Ids.Research.MedicalSupplies2, new Vector2i(96, 48));
      this.setPosition(Ids.Research.MedicalSupplies3, new Vector2i(116, 48));
      this.setPosition(Ids.Research.CaptainsOffice, new Vector2i(12, 38));
      this.setPosition(Ids.Research.Tools, new Vector2i(4, 32));
      this.setPosition(Ids.Research.Blueprints, new Vector2i(16, 42));
      this.setPosition(Ids.Research.TerrainLeveling, new Vector2i(28, 22));
      this.setPosition(Ids.Research.Edicts1, new Vector2i(24, 38));
      this.setPosition(Ids.Research.Edicts2, new Vector2i(36, 38));
      this.setPosition(Ids.Research.CaptainsOffice2, new Vector2i(48, 38));
      this.setPosition(Ids.Research.Edicts3, new Vector2i(56, 38));
      this.setPosition(Ids.Research.Edicts4, new Vector2i(64, 38));
      this.setPosition(Ids.Research.ResearchLab2, new Vector2i(28, 18));
      this.setPosition(Ids.Research.ResearchLab3, new Vector2i(56, 18));
      this.setPosition(Ids.Research.ResearchLab4, new Vector2i(88, 18));
      this.setPosition(Ids.Research.ResearchLab5, new Vector2i(112, 18));
      this.setPosition(Ids.Research.Datacenter, new Vector2i(112, 13));
      this.setPosition(Ids.Research.VehicleCapIncrease, new Vector2i(24, 17));
      this.setPosition(Ids.Research.VehicleCapIncrease2, new Vector2i(36, 24));
      this.setPosition(Ids.Research.TradeDock, new Vector2i(4, 26));
      this.setPosition(Ids.Research.CargoDepot, new Vector2i(32, 18));
      this.setPosition(Ids.Research.TrucksCapacityEdict, new Vector2i(64, 26));
      this.setPosition(Ids.Research.VehicleCapIncrease3, new Vector2i(52, 40));
      this.setPosition(Ids.Research.VehicleCapIncrease4, new Vector2i(60, 26));
      this.setPosition(Ids.Research.VehicleCapIncrease5, new Vector2i(92, 29));
      this.setPosition(Ids.Research.VehicleCapIncrease6, new Vector2i(116, 11));
      this.setPosition(Ids.Research.AdvancedLogisticsControl, new Vector2i(24, 22));
      this.setPosition(Ids.Research.PipeTransports, new Vector2i(0, 38));
      this.setPosition(Ids.Research.PipeTransportsT2, new Vector2i(32, 14));
      this.setPosition(Ids.Research.PipeTransportsT3, new Vector2i(72, 27));
      this.setPosition(Ids.Research.Storage2, new Vector2i(36, 18));
      this.setPosition(Ids.Research.Storage3, new Vector2i(60, 8));
      this.setPosition(Ids.Research.Storage4, new Vector2i(92, 6));
      this.setPosition(Ids.Research.CargoDepot2, new Vector2i(48, 28));
      this.setPosition(Ids.Research.CargoDepot3, new Vector2i(96, 6));
      this.setPosition(Ids.Research.CargoDepot4, new Vector2i(116, 7));
      this.setPosition(Ids.Research.FuelStation, new Vector2i(20, 22));
      this.setPosition(Ids.Research.FuelStation2, new Vector2i(52, 14));
      this.setPosition(Ids.Research.FuelStation3, new Vector2i(96, 10));
      this.setPosition(Ids.Research.ConveyorBelts, new Vector2i(20, 9));
      this.setPosition(Ids.Research.ConveyorBeltsT2, new Vector2i(48, 10));
      this.setPosition(Ids.Research.ConveyorBeltsT3, new Vector2i(92, 23));
      this.setPosition(Ids.Research.VehicleRamps, new Vector2i(16, 32));
      this.setPosition(Ids.Research.Stacker, new Vector2i(32, 5));
      this.setPosition(Ids.Research.TransportsBalancing, new Vector2i(24, 9));
      this.setPosition(Ids.Research.TransportsLifts, new Vector2i(24, 13));
      this.setPosition(Ids.Research.VehicleAssembly2, new Vector2i(48, 14));
      this.setPosition(Ids.Research.HydrogenCell, new Vector2i(72, 10));
      this.setPosition(Ids.Research.VehicleAssembly3, new Vector2i(92, 10));
      this.setPosition(Ids.Research.VehicleAssembly3H, new Vector2i(96, 14));
      this.setPosition(Ids.Research.ConveyorRouting, new Vector2i(28, 9));
      this.setPosition(Ids.Research.IronSmeltingScrap, new Vector2i(0, 9));
      this.setPosition(Ids.Research.SettlementWaste, new Vector2i(0, 32));
      this.setPosition(Ids.Research.VehicleAndMining, new Vector2i(4, 9));
      this.setPosition(Ids.Research.CopperRefinement, new Vector2i(12, 15));
      this.setPosition(Ids.Research.ConcreteAdvanced, new Vector2i(24, 5));
      this.setPosition(Ids.Research.SteelSmelting, new Vector2i(40, 12));
      this.setPosition(Ids.Research.ExhaustFiltration, new Vector2i(72, 31));
      this.setPosition(Ids.Research.CopperRefinement2, new Vector2i(52, 22));
      this.setPosition(Ids.Research.GlassSmelting, new Vector2i(68, 18));
      this.setPosition(Ids.Research.HouseholdGoods, new Vector2i(76, 14));
      this.setPosition(Ids.Research.AdvancedSmelting, new Vector2i(76, 21));
      this.setPosition(Ids.Research.CrusherLarge, new Vector2i(80, 23));
      this.setPosition(Ids.Research.IndustrialMixerT2, new Vector2i(80, 14));
      this.setPosition(Ids.Research.GlassSmeltingT2, new Vector2i(100, 21));
      this.setPosition(Ids.Research.PolySiliconProduction, new Vector2i(80, 18));
      this.setPosition(Ids.Research.ArcFurnace2, new Vector2i(116, 21));
      this.setPosition(Ids.Research.GoldSmelting, new Vector2i(96, 18));
      this.setPosition(Ids.Research.RecyclingIncrease, new Vector2i(68, 5));
      this.setPosition(Ids.Research.RecyclingEdict, new Vector2i(64, 6));
      this.setPosition(Ids.Research.RecyclingEdict2, new Vector2i(96, 27));
      this.setPosition(Ids.Research.Electricity, new Vector2i(0, 15));
      this.setPosition(Ids.Research.PowerAndMaintenance, new Vector2i(4, 15));
      this.setPosition(Ids.Research.Beacon, new Vector2i(8, 21));
      this.setPosition(Ids.Research.PowerGeneration2, new Vector2i(32, 34));
      this.setPosition(Ids.Research.DieselGeneratorLarge, new Vector2i(48, 32));
      this.setPosition(Ids.Research.BoilerElectric, new Vector2i(100, 32));
      this.setPosition(Ids.Research.PowerGeneration3, new Vector2i(60, 34));
      this.setPosition(Ids.Research.PowerGeneration4, new Vector2i(88, 34));
      this.setPosition(Ids.Research.WaterRecovery, new Vector2i(52, 34));
      this.setPosition(Ids.Research.ThermalStorage, new Vector2i(64, 31));
      this.setPosition(Ids.Research.UraniumEnrichment, new Vector2i(92, 34));
      this.setPosition(Ids.Research.NuclearReactor, new Vector2i(96, 34));
      this.setPosition(Ids.Research.NuclearReactor2, new Vector2i(112, 34));
      this.setPosition(Ids.Research.NuclearReactor3, new Vector2i(129, 34));
      this.setPosition(Ids.Research.SolarPanels, new Vector2i(88, 30));
      this.setPosition(Ids.Research.SolarPanels2, new Vector2i(125, 24));
      this.setPosition(Ids.Research.BasicDiesel, new Vector2i(8, 26));
      this.setPosition(Ids.Research.CrudeOilDistillation, new Vector2i(32, 22));
      this.setPosition(Ids.Research.SulfurProcessing, new Vector2i(48, 22));
      this.setPosition(Ids.Research.GasCombustion, new Vector2i(40, 30));
      this.setPosition(Ids.Research.Biofuel, new Vector2i(32, 26));
      this.setPosition(Ids.Research.BioDiesel, new Vector2i(64, 46));
      this.setPosition(Ids.Research.NaphthaProcessing, new Vector2i(60, 14));
      this.setPosition(Ids.Research.NaphthaReforming, new Vector2i(64, 12));
      this.setPosition(Ids.Research.HydrogenReforming, new Vector2i(68, 12));
      this.setPosition(Ids.Research.IncinerationPlant, new Vector2i(68, 30));
      this.setPosition(Ids.Research.RubberProduction, new Vector2i(12, 26));
      this.setPosition(Ids.Research.PlasticProduction, new Vector2i(68, 22));
      this.setPosition(Ids.Research.HouseholdAppliances, new Vector2i(88, 23));
      this.setPosition(Ids.Research.ConsumerElectronics, new Vector2i(125, 18));
      this.setPosition(Ids.Research.SuperPressSteam, new Vector2i(120, 30));
      this.setPosition(Ids.Research.ShipWeapons, new Vector2i(36, 4));
      this.setPosition(Ids.Research.ShipArmor, new Vector2i(40, 4));
      this.setPosition(Ids.Research.ShipRadar, new Vector2i(60, 3));
      this.setPosition(Ids.Research.Engine2, new Vector2i(72, 3));
      this.setPosition(Ids.Research.ShipWeapons2, new Vector2i(88, 3));
      this.setPosition(Ids.Research.ShipFuelTankUpgrade, new Vector2i(104, 0));
      this.setPosition(Ids.Research.ShipArmor2, new Vector2i(108, 3));
      this.setPosition(Ids.Research.ShipRadar2, new Vector2i(100, 0));
      this.setPosition(Ids.Research.Engine3, new Vector2i(120, 3));
      this.setPosition(Ids.Research.ShipWeapons3, new Vector2i(129, 3));
      this.setPosition(Ids.Research.RocketAssemblyAndLaunch, new Vector2i(125, 12));
      this.setParent(Ids.Research.CpPacking, Ids.Research.PowerAndMaintenance);
      this.setParent(Ids.Research.Recycling, Ids.Research.Compactor);
      this.setParent(Ids.Research.Recycling, Ids.Research.RecyclingEdict);
      this.setParent(Ids.Research.BricksProduction, Ids.Research.CopperRefinement);
      this.setParent(Ids.Research.RetainingWalls, Ids.Research.Stacker);
      this.setParent(Ids.Research.Cp2Packing, Ids.Research.FarmingT2);
      this.setParent(Ids.Research.Cp2Packing, Ids.Research.CropRotation);
      this.setParent(Ids.Research.Cp2Packing, Ids.Research.UndergroundWater);
      this.setParent(Ids.Research.Cp2Packing, Ids.Research.ResearchLab2);
      this.setParent(Ids.Research.Cp2Packing, Ids.Research.FuelStation);
      this.setParent(Ids.Research.Cp2Packing, Ids.Research.ConveyorBelts);
      this.setParent(Ids.Research.Cp2Packing, Ids.Research.ConcreteAdvanced);
      this.setParent(Ids.Research.SettlementWater, Ids.Research.Housing2);
      this.setParent(Ids.Research.Cp3Packing, Ids.Research.Recycling);
      this.setParent(Ids.Research.Cp3Packing, Ids.Research.CaptainsOffice2);
      this.setParent(Ids.Research.Cp3Packing, Ids.Research.ResearchLab3);
      this.setParent(Ids.Research.Cp3Packing, Ids.Research.CargoDepot2);
      this.setParent(Ids.Research.Cp3Packing, Ids.Research.ConveyorBeltsT2);
      this.setParent(Ids.Research.Cp3Packing, Ids.Research.VehicleAssembly2);
      this.setParent(Ids.Research.Cp3Packing, Ids.Research.DieselGeneratorLarge);
      this.setParent(Ids.Research.Cp3Packing, Ids.Research.WaterRecovery);
      this.setParent(Ids.Research.Cp3Packing, Ids.Research.SulfurProcessing);
      this.setParent(Ids.Research.Cp4Packing, Ids.Research.StatueOfMaintenance);
      this.setParent(Ids.Research.Cp4Packing, Ids.Research.ResearchLab4);
      this.setParent(Ids.Research.Cp4Packing, Ids.Research.PowerGeneration4);
      this.setParent(Ids.Research.Cp4Packing, Ids.Research.SolarPanels);
      this.setParent(Ids.Research.Cp4Packing, Ids.Research.HouseholdAppliances);
      this.setParent(Ids.Research.BasicComputing, Ids.Research.MicrochipProduction);
      this.setParent(Ids.Research.BasicComputing, Ids.Research.NuclearReactor2);
      this.setParent(Ids.Research.Housing3, Ids.Research.SettlementDecorations);
      this.setParent(Ids.Research.Housing3, Ids.Research.HouseholdGoods);
      this.setParent(Ids.Research.Assembler3, Ids.Research.SolarPanels2);
      this.setParent(Ids.Research.Assembler3, Ids.Research.ConsumerElectronics);
      this.setParent(Ids.Research.Assembler3, Ids.Research.RocketAssemblyAndLaunch);
      this.setParent(Ids.Research.MicrochipProduction, Ids.Research.ResearchLab5);
      this.setParent(Ids.Research.MicrochipProduction, Ids.Research.Datacenter);
      this.setParent(Ids.Research.BasicFarming, Ids.Research.TradeDock);
      this.setParent(Ids.Research.FarmingT2, Ids.Research.TreePlanting);
      this.setParent(Ids.Research.CropRotation, Ids.Research.TreePlanting);
      this.setParent(Ids.Research.CropRotation, Ids.Research.Vegetables);
      this.setParent(Ids.Research.FarmingT3, Ids.Research.FarmingT4);
      this.setParent(Ids.Research.FarmingT3, Ids.Research.SugarCane);
      this.setParent(Ids.Research.FarmingT3, Ids.Research.Fruit);
      this.setParent(Ids.Research.Burner, Ids.Research.WheatCrop);
      this.setParent(Ids.Research.Vegetables, Ids.Research.WheatCrop);
      this.setParent(Ids.Research.CornCrop, Ids.Research.Fermentation);
      this.setParent(Ids.Research.WheatCrop, Ids.Research.CornCrop);
      this.setParent(Ids.Research.WheatCrop, Ids.Research.SoybeanCrop);
      this.setParent(Ids.Research.WheatCrop, Ids.Research.ChickenFarm);
      this.setParent(Ids.Research.WheatCrop, Ids.Research.OrganicFertilizer);
      this.setParent(Ids.Research.SoybeanCrop, Ids.Research.BioDiesel);
      this.setParent(Ids.Research.SugarCane, Ids.Research.MedicalSupplies2);
      this.setParent(Ids.Research.ChickenFarm, Ids.Research.SausageProduction);
      this.setParent(Ids.Research.SnacksProduction, Ids.Research.FoodPacking);
      this.setParent(Ids.Research.UndergroundWater, Ids.Research.SettlementWater);
      this.setParent(Ids.Research.UndergroundWater, Ids.Research.PowerGeneration2);
      this.setParent(Ids.Research.WaterTreatment, Ids.Research.PipeTransportsT3);
      this.setParent(Ids.Research.WaterTreatment, Ids.Research.ExhaustFiltration);
      this.setParent(Ids.Research.WaterTreatment2, Ids.Research.VacuumDesalination);
      this.setParent(Ids.Research.SaltProduction, Ids.Research.Electrolysis);
      this.setParent(Ids.Research.SaltProduction, Ids.Research.GlassSmelting);
      this.setParent(Ids.Research.SaltProduction, Ids.Research.ThermalStorage);
      this.setParent(Ids.Research.ChemicalPlant, Ids.Research.Fertilizers);
      this.setParent(Ids.Research.ChemicalPlant, Ids.Research.ResearchLab3);
      this.setParent(Ids.Research.Electrolysis, Ids.Research.WaterTreatment);
      this.setParent(Ids.Research.Electrolysis, Ids.Research.IncinerationPlant);
      this.setParent(Ids.Research.Electrolysis, Ids.Research.PlasticProduction);
      this.setParent(Ids.Research.Fermentation, Ids.Research.Hospital);
      this.setParent(Ids.Research.Fermentation, Ids.Research.BioDiesel);
      this.setParent(Ids.Research.Hospital, Ids.Research.MedicalSupplies2);
      this.setParent(Ids.Research.MedicalSupplies2, Ids.Research.MedicalSupplies3);
      this.setParent(Ids.Research.CaptainsOffice, Ids.Research.Blueprints);
      this.setParent(Ids.Research.CaptainsOffice, Ids.Research.Edicts1);
      this.setParent(Ids.Research.Tools, Ids.Research.CaptainsOffice);
      this.setParent(Ids.Research.Edicts1, Ids.Research.Edicts2);
      this.setParent(Ids.Research.Edicts2, Ids.Research.CaptainsOffice2);
      this.setParent(Ids.Research.CaptainsOffice2, Ids.Research.Edicts3);
      this.setParent(Ids.Research.CaptainsOffice2, Ids.Research.VehicleCapIncrease3);
      this.setParent(Ids.Research.Edicts3, Ids.Research.Edicts4);
      this.setParent(Ids.Research.ResearchLab2, Ids.Research.MaintenanceDepot);
      this.setParent(Ids.Research.ResearchLab2, Ids.Research.Burner);
      this.setParent(Ids.Research.ResearchLab2, Ids.Research.ThermalDesalinationBasic);
      this.setParent(Ids.Research.ResearchLab2, Ids.Research.Edicts2);
      this.setParent(Ids.Research.ResearchLab2, Ids.Research.VehicleCapIncrease2);
      this.setParent(Ids.Research.ResearchLab2, Ids.Research.CargoDepot);
      this.setParent(Ids.Research.ResearchLab2, Ids.Research.PipeTransportsT2);
      this.setParent(Ids.Research.ResearchLab2, Ids.Research.SteelSmelting);
      this.setParent(Ids.Research.ResearchLab2, Ids.Research.PowerGeneration2);
      this.setParent(Ids.Research.ResearchLab2, Ids.Research.CrudeOilDistillation);
      this.setParent(Ids.Research.ResearchLab2, Ids.Research.Biofuel);
      this.setParent(Ids.Research.ResearchLab3, Ids.Research.ChickenFarm);
      this.setParent(Ids.Research.ResearchLab3, Ids.Research.SaltProduction);
      this.setParent(Ids.Research.ResearchLab3, Ids.Research.ThermalDesalination);
      this.setParent(Ids.Research.ResearchLab3, Ids.Research.Fermentation);
      this.setParent(Ids.Research.ResearchLab3, Ids.Research.Edicts4);
      this.setParent(Ids.Research.ResearchLab3, Ids.Research.VehicleCapIncrease4);
      this.setParent(Ids.Research.ResearchLab3, Ids.Research.Storage3);
      this.setParent(Ids.Research.ResearchLab3, Ids.Research.RecyclingEdict);
      this.setParent(Ids.Research.ResearchLab3, Ids.Research.PowerGeneration3);
      this.setParent(Ids.Research.ResearchLab3, Ids.Research.NaphthaProcessing);
      this.setParent(Ids.Research.ResearchLab3, Ids.Research.ShipRadar);
      this.setParent(Ids.Research.ResearchLab4, Ids.Research.TombOfCaptains);
      this.setParent(Ids.Research.ResearchLab4, Ids.Research.SugarCane);
      this.setParent(Ids.Research.ResearchLab4, Ids.Research.SausageProduction);
      this.setParent(Ids.Research.ResearchLab4, Ids.Research.WaterTreatment2);
      this.setParent(Ids.Research.ResearchLab4, Ids.Research.ChemicalPlant2);
      this.setParent(Ids.Research.ResearchLab4, Ids.Research.VehicleCapIncrease5);
      this.setParent(Ids.Research.ResearchLab4, Ids.Research.Storage4);
      this.setParent(Ids.Research.ResearchLab4, Ids.Research.ConveyorBeltsT3);
      this.setParent(Ids.Research.ResearchLab4, Ids.Research.VehicleAssembly3);
      this.setParent(Ids.Research.ResearchLab4, Ids.Research.GlassSmeltingT2);
      this.setParent(Ids.Research.ResearchLab4, Ids.Research.GoldSmelting);
      this.setParent(Ids.Research.ResearchLab4, Ids.Research.RecyclingEdict2);
      this.setParent(Ids.Research.ResearchLab4, Ids.Research.BoilerElectric);
      this.setParent(Ids.Research.ResearchLab4, Ids.Research.UraniumEnrichment);
      this.setParent(Ids.Research.ResearchLab4, Ids.Research.ShipArmor2);
      this.setParent(Ids.Research.ResearchLab5, Ids.Research.Assembler3);
      this.setParent(Ids.Research.ResearchLab5, Ids.Research.MicrochipProduction2);
      this.setParent(Ids.Research.ResearchLab5, Ids.Research.CarbonDioxideRecycling);
      this.setParent(Ids.Research.ResearchLab5, Ids.Research.MedicalSupplies3);
      this.setParent(Ids.Research.ResearchLab5, Ids.Research.VehicleCapIncrease6);
      this.setParent(Ids.Research.ResearchLab5, Ids.Research.CargoDepot4);
      this.setParent(Ids.Research.ResearchLab5, Ids.Research.ArcFurnace2);
      this.setParent(Ids.Research.ResearchLab5, Ids.Research.SuperPressSteam);
      this.setParent(Ids.Research.ResearchLab5, Ids.Research.Engine3);
      this.setParent(Ids.Research.TradeDock, Ids.Research.BricksProduction);
      this.setParent(Ids.Research.CargoDepot, Ids.Research.Storage2);
      this.setParent(Ids.Research.CargoDepot, Ids.Research.CargoDepot2);
      this.setParent(Ids.Research.VehicleCapIncrease4, Ids.Research.TrucksCapacityEdict);
      this.setParent(Ids.Research.AdvancedLogisticsControl, Ids.Research.TerrainLeveling);
      this.setParent(Ids.Research.Storage2, Ids.Research.FoodMarket2);
      this.setParent(Ids.Research.Storage4, Ids.Research.CargoDepot3);
      this.setParent(Ids.Research.FuelStation, Ids.Research.AdvancedLogisticsControl);
      this.setParent(Ids.Research.FuelStation2, Ids.Research.HydrogenCell);
      this.setParent(Ids.Research.ConveyorBelts, Ids.Research.TransportsBalancing);
      this.setParent(Ids.Research.ConveyorBelts, Ids.Research.TransportsLifts);
      this.setParent(Ids.Research.TransportsBalancing, Ids.Research.ConveyorRouting);
      this.setParent(Ids.Research.VehicleAssembly2, Ids.Research.FuelStation2);
      this.setParent(Ids.Research.VehicleAssembly3, Ids.Research.FuelStation3);
      this.setParent(Ids.Research.VehicleAssembly3, Ids.Research.VehicleAssembly3H);
      this.setParent(Ids.Research.IronSmeltingScrap, Ids.Research.VehicleAndMining);
      this.setParent(Ids.Research.VehicleAndMining, Ids.Research.BricksProduction);
      this.setParent(Ids.Research.CopperRefinement, Ids.Research.Cp2Packing);
      this.setParent(Ids.Research.ConcreteAdvanced, Ids.Research.CustomSurfaces);
      this.setParent(Ids.Research.ConcreteAdvanced, Ids.Research.RetainingWalls);
      this.setParent(Ids.Research.SteelSmelting, Ids.Research.Cp3Packing);
      this.setParent(Ids.Research.SteelSmelting, Ids.Research.ShipRadar);
      this.setParent(Ids.Research.GlassSmelting, Ids.Research.Housing3);
      this.setParent(Ids.Research.GlassSmelting, Ids.Research.FarmingT3);
      this.setParent(Ids.Research.GlassSmelting, Ids.Research.Hospital);
      this.setParent(Ids.Research.GlassSmelting, Ids.Research.AdvancedSmelting);
      this.setParent(Ids.Research.GlassSmelting, Ids.Research.PolySiliconProduction);
      this.setParent(Ids.Research.HouseholdGoods, Ids.Research.RecyclingForSettlement);
      this.setParent(Ids.Research.AdvancedSmelting, Ids.Research.CrusherLarge);
      this.setParent(Ids.Research.AdvancedSmelting, Ids.Research.IndustrialMixerT2);
      this.setParent(Ids.Research.AdvancedSmelting, Ids.Research.GlassSmeltingT2);
      this.setParent(Ids.Research.GlassSmeltingT2, Ids.Research.FarmingT4);
      this.setParent(Ids.Research.PolySiliconProduction, Ids.Research.Cp4Packing);
      this.setParent(Ids.Research.PolySiliconProduction, Ids.Research.Electrolysis2);
      this.setParent(Ids.Research.GoldSmelting, Ids.Research.BasicComputing);
      this.setParent(Ids.Research.RecyclingEdict, Ids.Research.RecyclingForSettlement);
      this.setParent(Ids.Research.RecyclingEdict, Ids.Research.RecyclingIncrease);
      this.setParent(Ids.Research.Electricity, Ids.Research.PowerAndMaintenance);
      this.setParent(Ids.Research.PowerAndMaintenance, Ids.Research.BricksProduction);
      this.setParent(Ids.Research.PowerAndMaintenance, Ids.Research.CaptainsOffice);
      this.setParent(Ids.Research.PowerAndMaintenance, Ids.Research.Beacon);
      this.setParent(Ids.Research.PowerAndMaintenance, Ids.Research.BasicDiesel);
      this.setParent(Ids.Research.Beacon, Ids.Research.RepairDock);
      this.setParent(Ids.Research.PowerGeneration2, Ids.Research.SettlementPower);
      this.setParent(Ids.Research.PowerGeneration2, Ids.Research.WaterRecovery);
      this.setParent(Ids.Research.PowerGeneration2, Ids.Research.GasCombustion);
      this.setParent(Ids.Research.PowerGeneration3, Ids.Research.PowerGeneration4);
      this.setParent(Ids.Research.PowerGeneration4, Ids.Research.BoilerElectric);
      this.setParent(Ids.Research.PowerGeneration4, Ids.Research.UraniumEnrichment);
      this.setParent(Ids.Research.WaterRecovery, Ids.Research.PowerGeneration3);
      this.setParent(Ids.Research.UraniumEnrichment, Ids.Research.NuclearReactor);
      this.setParent(Ids.Research.NuclearReactor, Ids.Research.NuclearReactor2);
      this.setParent(Ids.Research.NuclearReactor2, Ids.Research.NuclearReactor3);
      this.setParent(Ids.Research.BasicDiesel, Ids.Research.VehicleRamps);
      this.setParent(Ids.Research.BasicDiesel, Ids.Research.RubberProduction);
      this.setParent(Ids.Research.CrudeOilDistillation, Ids.Research.SulfurProcessing);
      this.setParent(Ids.Research.CrudeOilDistillation, Ids.Research.GasCombustion);
      this.setParent(Ids.Research.CrudeOilDistillation, Ids.Research.ShipWeapons);
      this.setParent(Ids.Research.SulfurProcessing, Ids.Research.SoybeanCrop);
      this.setParent(Ids.Research.SulfurProcessing, Ids.Research.ChemicalPlant);
      this.setParent(Ids.Research.SulfurProcessing, Ids.Research.CopperRefinement2);
      this.setParent(Ids.Research.BioDiesel, Ids.Research.Canola);
      this.setParent(Ids.Research.NaphthaProcessing, Ids.Research.RotaryKilnGas);
      this.setParent(Ids.Research.NaphthaProcessing, Ids.Research.NaphthaReforming);
      this.setParent(Ids.Research.NaphthaReforming, Ids.Research.HydrogenReforming);
      this.setParent(Ids.Research.HydrogenReforming, Ids.Research.HydrogenCell);
      this.setParent(Ids.Research.RubberProduction, Ids.Research.Cp2Packing);
      this.setParent(Ids.Research.PlasticProduction, Ids.Research.SnacksProduction);
      this.setParent(Ids.Research.PlasticProduction, Ids.Research.Hospital);
      this.setParent(Ids.Research.PlasticProduction, Ids.Research.PolySiliconProduction);
      this.setParent(Ids.Research.SuperPressSteam, Ids.Research.NuclearReactor3);
      this.setParent(Ids.Research.ShipWeapons, Ids.Research.ShipArmor);
      this.setParent(Ids.Research.ShipRadar, Ids.Research.Engine2);
      this.setParent(Ids.Research.Engine2, Ids.Research.ShipWeapons2);
      this.setParent(Ids.Research.ShipWeapons2, Ids.Research.ShipArmor2);
      this.setParent(Ids.Research.ShipWeapons2, Ids.Research.ShipRadar2);
      this.setParent(Ids.Research.ShipArmor2, Ids.Research.Engine3);
      this.setParent(Ids.Research.ShipRadar2, Ids.Research.ShipFuelTankUpgrade);
      this.setParent(Ids.Research.Engine3, Ids.Research.ShipWeapons3);
    }

    private void setPosition(ResearchNodeProto.ID nodeId, Vector2i nodePos)
    {
      Option<ResearchNodeProto> option = this.m_protosDb.Get<ResearchNodeProto>((Proto.ID) nodeId);
      if (option.IsNone)
        Log.Warning(string.Format("Failed to set position of research node: {0}", (object) nodeId));
      else
        option.Value.GridPosition = nodePos;
    }

    private void setParent(ResearchNodeProto.ID parent, ResearchNodeProto.ID of)
    {
      Option<ResearchNodeProto> option1 = this.m_protosDb.Get<ResearchNodeProto>((Proto.ID) parent);
      Option<ResearchNodeProto> option2 = this.m_protosDb.Get<ResearchNodeProto>((Proto.ID) of);
      if (option1.IsNone || option2.IsNone)
        Log.Warning(string.Format("Failed to set research relationship: {0} => {1}", (object) of, (object) parent));
      else
        option2.Value.AddParent(option1.Value);
    }
  }
}
