// Decompiled with JetBrains decompiler
// Type: Mafi.Unity.UiToolkit.Cls
// Assembly: Mafi.Unity, Version=0.6.3.0, Culture=neutral, PublicKeyToken=null
// MVID: E477F8BD-C838-4DE6-805D-A367452B274A
// Assembly location: D:\GameLibrary\SteamLibrary\steamapps\common\Captain of Industry\Captain of Industry_Data\Managed\Mafi.Unity.dll
// XML documentation location: D:\GameLibrary\SteamLibrary\steamapps\common\Captain of Industry\Captain of Industry_Data\Managed\Mafi.Unity.xml

using ut12pZTdSUNA6wM24P;

#nullable disable
namespace Mafi.Unity.UiToolkit
{
  public static class Cls
  {
    public static readonly string editor;
    public static readonly string inputDropdown;
    public static readonly string inputDropdown_btn;
    public static readonly string inputTextWrapper;
    public static readonly string inputText;
    public static readonly string inputToggle;
    public static readonly string notStandalone;
    public static readonly string inputToggle_btnHolder;
    public static readonly string row;
    public static readonly string inputDropdown_popup;
    public static readonly string inputToggle_btn;
    public static readonly string error;
    public static readonly string inputLabel;
    public static readonly string inline;
    public static readonly string inputDropdown_option;
    public static readonly string inputText_field;
    public static readonly string noCheck;
    public static readonly string inputDropdown_btn_arrow;
    public static readonly string icon;
    public static readonly string selected;
    public static readonly string inGlow;
    public static readonly string inputDropdown_option_line;
    public static readonly string inputDropdown_option_tick;
    public static readonly string standalone;
    public static readonly string clickable;
    public static readonly string column;
    public static readonly string multiline;
    public static readonly string readonlyCls;
    public static readonly string attachedIcon;
    public static readonly string attachedIconLeft;
    public static readonly string pendingEditIcon;
    public static readonly string inputText_field_placeholder;
    public static readonly string slider;
    public static readonly string slider_track;
    public static readonly string slider_fill;
    public static readonly string slider_thumbShadow;
    public static readonly string slider_thumb;
    public static readonly string panel0;
    public static readonly string panel1;
    public static readonly string editorLabel;
    public static readonly string collapsed;
    public static readonly string header;
    public static readonly string editorLabel0;
    public static readonly string collapsible;
    public static readonly string editorLabel1;
    public static readonly string dragHandle;
    public static readonly string fadeIn;
    public static readonly string show;
    public static readonly string slideIn;
    public static readonly string fromTop;
    public static readonly string mask;
    public static readonly string dark;
    public static readonly string flipNotches;
    public static readonly string shadowCutCorner;
    public static readonly string toggle;
    public static readonly string glowOnHover;
    public static readonly string outlined;
    public static readonly string listGroup;
    public static readonly string btn_area;
    public static readonly string btn_primary;
    public static readonly string btn_default;
    public static readonly string bold;
    public static readonly string btn_boxy;
    public static readonly string iconClickable;
    public static readonly string shadow;
    public static readonly string primary;
    public static readonly string growOnHover;
    public static readonly string alignItemsCenter;
    public static readonly string warningText;
    public static readonly string invalid;
    public static readonly string title;
    public static readonly string dropdown__popup;
    public static readonly string dropdown__popup__item;
    public static readonly string showOnHover_container;
    public static readonly string showOnHover_target;
    public static readonly string window;
    public static readonly string windowBorder;
    public static readonly string diamondPattern;
    public static readonly string windowShadow;
    public static readonly string window__title;
    public static readonly string windowCloseButton;
    public static readonly string outer;
    public static readonly string window__body;
    public static readonly string panel;
    public static readonly string body;
    public static readonly string window__rootPanel;
    public static readonly string background;
    public static readonly string noBolts;
    public static readonly string bolts;
    public static readonly string tabContainer;
    public static readonly string tabbed;
    public static readonly string panelTab;
    public static readonly string panelTab_inputDropdown;
    public static readonly string panelBolt;
    public static readonly string edgeShadow;
    public static readonly string top;
    public static readonly string bottom;
    public static readonly string bulletedList;
    public static readonly string noIndent;
    public static readonly string bulletedList_item;
    public static readonly string large;
    public static readonly string medium;
    public static readonly string img;
    public static readonly string small;
    public static readonly string errorIcon;
    public static readonly string absoluteMiddle;
    public static readonly string absoluteCenter;
    public static readonly string absoluteCenterMiddle;
    public static readonly string outShadow;
    public static readonly string shadowAll;
    public static readonly string shadowBottom;
    public static readonly string glowAll;
    public static readonly string glowError;
    public static readonly string inShadow;
    public static readonly string shadowLtr;

    static Cls()
    {
      xxhJUtQyC9HnIshc6H.OukgcisAbr();
      Cls.editor = nameof (editor);
      Cls.inputDropdown = nameof (inputDropdown);
      Cls.inputDropdown_btn = nameof (inputDropdown_btn);
      Cls.inputTextWrapper = nameof (inputTextWrapper);
      Cls.inputText = nameof (inputText);
      Cls.inputToggle = nameof (inputToggle);
      Cls.notStandalone = nameof (notStandalone);
      Cls.inputToggle_btnHolder = nameof (inputToggle_btnHolder);
      Cls.row = nameof (row);
      Cls.inputDropdown_popup = nameof (inputDropdown_popup);
      Cls.inputToggle_btn = nameof (inputToggle_btn);
      Cls.error = nameof (error);
      Cls.inputLabel = nameof (inputLabel);
      Cls.inline = nameof (inline);
      Cls.inputDropdown_option = nameof (inputDropdown_option);
      Cls.inputText_field = nameof (inputText_field);
      Cls.noCheck = nameof (noCheck);
      Cls.inputDropdown_btn_arrow = nameof (inputDropdown_btn_arrow);
      Cls.icon = nameof (icon);
      Cls.selected = nameof (selected);
      Cls.inGlow = nameof (inGlow);
      Cls.inputDropdown_option_line = nameof (inputDropdown_option_line);
      Cls.inputDropdown_option_tick = nameof (inputDropdown_option_tick);
      Cls.standalone = nameof (standalone);
      Cls.clickable = nameof (clickable);
      Cls.column = nameof (column);
      Cls.multiline = nameof (multiline);
      Cls.readonlyCls = "readonly";
      Cls.attachedIcon = nameof (attachedIcon);
      Cls.attachedIconLeft = nameof (attachedIconLeft);
      Cls.pendingEditIcon = nameof (pendingEditIcon);
      Cls.inputText_field_placeholder = nameof (inputText_field_placeholder);
      Cls.slider = nameof (slider);
      Cls.slider_track = nameof (slider_track);
      Cls.slider_fill = nameof (slider_fill);
      Cls.slider_thumbShadow = nameof (slider_thumbShadow);
      Cls.slider_thumb = nameof (slider_thumb);
      Cls.panel0 = nameof (panel0);
      Cls.panel1 = nameof (panel1);
      Cls.editorLabel = nameof (editorLabel);
      Cls.collapsed = nameof (collapsed);
      Cls.header = nameof (header);
      Cls.editorLabel0 = nameof (editorLabel0);
      Cls.collapsible = nameof (collapsible);
      Cls.editorLabel1 = nameof (editorLabel1);
      Cls.dragHandle = nameof (dragHandle);
      Cls.fadeIn = nameof (fadeIn);
      Cls.show = nameof (show);
      Cls.slideIn = nameof (slideIn);
      Cls.fromTop = nameof (fromTop);
      Cls.mask = nameof (mask);
      Cls.dark = nameof (dark);
      Cls.flipNotches = nameof (flipNotches);
      Cls.shadowCutCorner = nameof (shadowCutCorner);
      Cls.toggle = nameof (toggle);
      Cls.glowOnHover = nameof (glowOnHover);
      Cls.outlined = nameof (outlined);
      Cls.listGroup = nameof (listGroup);
      Cls.btn_area = nameof (btn_area);
      Cls.btn_primary = nameof (btn_primary);
      Cls.btn_default = nameof (btn_default);
      Cls.bold = nameof (bold);
      Cls.btn_boxy = nameof (btn_boxy);
      Cls.iconClickable = nameof (iconClickable);
      Cls.shadow = nameof (shadow);
      Cls.primary = nameof (primary);
      Cls.growOnHover = nameof (growOnHover);
      Cls.alignItemsCenter = nameof (alignItemsCenter);
      Cls.warningText = nameof (warningText);
      Cls.invalid = nameof (invalid);
      Cls.title = nameof (title);
      Cls.dropdown__popup = nameof (dropdown__popup);
      Cls.dropdown__popup__item = nameof (dropdown__popup__item);
      Cls.showOnHover_container = nameof (showOnHover_container);
      Cls.showOnHover_target = nameof (showOnHover_target);
      Cls.window = nameof (window);
      Cls.windowBorder = nameof (windowBorder);
      Cls.diamondPattern = nameof (diamondPattern);
      Cls.windowShadow = nameof (windowShadow);
      Cls.window__title = nameof (window__title);
      Cls.windowCloseButton = nameof (windowCloseButton);
      Cls.outer = nameof (outer);
      Cls.window__body = nameof (window__body);
      Cls.panel = nameof (panel);
      Cls.body = nameof (body);
      Cls.window__rootPanel = nameof (window__rootPanel);
      Cls.background = nameof (background);
      Cls.noBolts = nameof (noBolts);
      Cls.bolts = nameof (bolts);
      Cls.tabContainer = nameof (tabContainer);
      Cls.tabbed = nameof (tabbed);
      Cls.panelTab = nameof (panelTab);
      Cls.panelTab_inputDropdown = nameof (panelTab_inputDropdown);
      Cls.panelBolt = nameof (panelBolt);
      Cls.edgeShadow = nameof (edgeShadow);
      Cls.top = nameof (top);
      Cls.bottom = nameof (bottom);
      Cls.bulletedList = nameof (bulletedList);
      Cls.noIndent = nameof (noIndent);
      Cls.bulletedList_item = nameof (bulletedList_item);
      Cls.large = nameof (large);
      Cls.medium = nameof (medium);
      Cls.img = nameof (img);
      Cls.small = nameof (small);
      Cls.errorIcon = nameof (errorIcon);
      Cls.absoluteMiddle = nameof (absoluteMiddle);
      Cls.absoluteCenter = nameof (absoluteCenter);
      Cls.absoluteCenterMiddle = nameof (absoluteCenterMiddle);
      Cls.outShadow = nameof (outShadow);
      Cls.shadowAll = nameof (shadowAll);
      Cls.shadowBottom = nameof (shadowBottom);
      Cls.glowAll = nameof (glowAll);
      Cls.glowError = nameof (glowError);
      Cls.inShadow = nameof (inShadow);
      Cls.shadowLtr = nameof (shadowLtr);
    }
  }
}
